version: '3.9'
services:
  db:
    image: postgres:16
    container_name: eventflow_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: eventflow
      POSTGRES_PASSWORD: eventflow
      POSTGRES_DB: eventflow
    ports:
      - "5433:5432"
    volumes:
      - pgdata_eventflow:/var/lib/postgresql/data
volumes:
  pgdata_eventflow:
